- name: "type: blocker"
  color: "3498DB"
  description: "A blocker for the release."
- name: "type: breaking-change"
  color: "3498DB"
  description: "A breaking change."
- name: "type: bug"
  color: "3498DB"
  description: "A bug."
- name: "type: dependency-upgrade"
  color: "3498DB"
  description: "A dependency upgrade."
- name: "type: deprecation"
  color: "3498DB"
  description: "A deprecation."
- name: "type: documentation"
  color: "3498DB"
  description: "A documentation update."
- name: "type: enhancement"
  color: "3498DB"
  description: "An enhancement."
- name: "type: epic"
  color: "3498DB"
  description: "An issue tracking a large piece of work to split into multiple issues."
- name: "type: regression"
  color: "3498DB"
  description: "A regression."
- name: "type: task"
  color: "3498DB"
  description: "A task to perform that should not appear in the changelog."
- name: "for: external-project"
  color: "27AE60"
  description: "For an external project and not something we can fix"
- name: "for: merge-with-amendments"
  color: "27AE60"
  description: "Needs some changes when we merge"
- name: "for: team-attention"
  color: "27AE60"
  description: "An issue we'd like other members of the team to review"
- name: "for: team-meeting"
  color: "27AE60"
  description: "An issue we'd like to discuss as a team to make progress"
- name: "status: back-port"
  color: "FFC300"
  description: "An issue tracking the back-port of a change made in an later branch"
- name: "status: front-port"
  color: "FFC300"
  description: "An issue tracking the front-port of a change made in an earlier branch"
- name: "status: blocked"
  color: "FFC300"
  description: "An issue that's blocked on an external project change"
- name: "status: declined"
  color: "FFC300"
  description: "A suggestion or change that we don't feel we should currently apply"
- name: "status: duplicate"
  color: "FFC300"
  description: "A duplicate of another issue"
- name: "status: feedback-provided"
  color: "FFC300"
  description: "Feedback has been provided"
- name: "status: feedback-reminder"
  color: "FFC300"
  description: "We've sent a reminder that we need additional information before we can continue"
- name: "status: ideal-for-contribution"
  color: "FFC300"
  description: "An issue that a contributor can help us with"
- name: "status: invalid"
  color: "FFC300"
  description: "An issue that we don't feel is valid"
- name: "status: noteworthy"
  color: "FFC300"
  description: "A noteworthy issue to call out in the release notes"
- name: "status: on-hold"
  color: "FFC300"
  description: "We can't start working on this issue yet"
- name: "status: pending-design-work"
  color: "FFC300"
  description: "Needs design work before any code can be developed"
- name: "status: waiting-for-feedback"
  color: "FFC300"
  description: "We need additional information before we can continue"
- name: "status: waiting-for-triage"
  color: "FFC300"
  description: "An issue we've not yet triaged"
