on: {push, pull_request}

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Building the project"
        run: echo "Nothing to do."
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
      - run: make install.dependencies lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Testing the project"
        run: echo "Nothing to do."