on:
  push:
    branches:
      - 'releases/**'

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - uses: actions/checkout@v2
    
    - name: Read current version
      id: current_vars
      run: |
        echo ::set-output name=version::$(make version.get-released)

    - name: Compute release vars
      id: release_vars
      uses: julb/action-prepare-release@v1
      with:
        version: ${{ steps.current_vars.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Linting
      run: make lint

    - name: Testing
      run: make test

    - name: Updating file versions
      run: make version.set VERSION=${{ steps.release_vars.outputs.version }}

    - name: Update CHANGELOG.md
      uses: heinrichreimer/github-changelog-generator-action@v2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        futureRelease: ${{ steps.release_vars.outputs.version }}
        addSections: '{"documentation":{"prefix":"📘 Documentation","labels":["type: documentation"]},"tests":{"prefix":"🏹 Dependency Upgrades","labels":["dependency-upgrade"]}}'
        issues: true
        issuesWoLabels: true
        pullRequests: true
        prWoLabels: true
        author: true
        filterByMilestone: true
        compareLink: true
        stripGeneratorNotice: true
        unreleased: true
        verbose: true
        excludeTagsRegex: ^(latest|v[0-9]+)$
        breakingLabel: "🔨 Breaking changes"
        breakingLabels: "type: breaking-change"
        enhancementLabel: "🚀 New features"
        enhancementLabels: "type: enhancement"
        bugsLabel: "🐞 Bug fixes"
        bugsLabels: "type: bug,type: regression"
        deprecateLabel: "👋 Deprecated"
        deprecatedLabels: "type: deprecation"

    - uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: "[ci] release version ${{ steps.release_vars.outputs.version }}"
        push: "origin ${{ steps.release_vars.outputs.version }}"
        tag: "${{ steps.release_vars.outputs.version }}"

    - name: Publish artifacts
      run: |
        make build
        make push

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@main
      with:
        configuration: ".github/config/changelog.json"
        toTag: "${{ steps.release_vars.outputs.version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_vars.outputs.version }}
        release_name: Release ${{ steps.release_vars.outputs.version }}
        body: ${{steps.github_release.outputs.changelog}}

    - name: Create major tag
      uses: julb/action-manage-tag@v1
      with:
        name: v${{ steps.release_vars.outputs.major_version }}
        state: present
        from: ${{ steps.release_vars.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create latest tag
      uses: julb/action-manage-tag@v1
      with:
        name: latest
        state: present
        from: ${{ steps.release_vars.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Merge back changes to target branch
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        target_branch: ${{ steps.release_vars.outputs.target_branch }}
        from_branch: ${{ steps.release_vars.outputs.version }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Switch back to target branch"
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.release_vars.outputs.target_branch }}
    
    - name: Bumping version
      id: next_vars
      run: |
        make version.bump
        echo ::set-output name=next_version::$(make version.get)
        echo ::set-output name=next_released_version::$(make version.get-released)

    - uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: "[ci] bump version ${{ steps.release_vars.outputs.version }} -> ${{ steps.next_vars.outputs.next_version }}"
        branch: "${{ steps.release_vars.outputs.target_branch }}"

    - name: "Close old milestone"
      uses: julb/action-manage-milestone@v1
      with:
        title: ${{ steps.release_vars.outputs.version }}
        state: 'closed'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Create new milestone"
      uses: julb/action-manage-milestone@v1
      with:
        title: ${{ steps.next_vars.outputs.next_released_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Drop release branch
      uses: julb/action-manage-branch@v1
      with:
        name: ${{ steps.release_vars.outputs.source_branch }}
        state: absent
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}