on: workflow_dispatch

name: Setup repository

jobs:
  setup-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Synchronize labels
      uses: julb/action-manage-label@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}